apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-qa
  labels:
    app: simple-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-qa
  template:
    metadata:
      labels:
        app: simple-qa
    spec:
      containers:
      - name: simple-qa-container
        image: containers.cisco.com/gudeng/genai-lab:latest  # Your Podman/OpenShift image name
        ports:
        - containerPort: 5601  # Updated port
        # env:  # Commented out as you're not using environment variables
        # - name: ENV_VAR_EXAMPLE  
        #   value: "value"

