apiVersion: v1
kind: Service
metadata:
  name: simple-qa-service  # Updated service name
spec:
  selector:
    app: simple-qa  # Updated to match the app name in the Deployment
  ports:
    - protocol: TCP
      port: 80           # Service port
      targetPort: 5601   # Updated to match the container port
      nodePort: 30080    # Optional: specify a port for external access (within the range of 30000-32767)
  type: LoadBalancer  # Use NodePort for external access

